png("plot3.png",width=480,height = 480)
with(EC,plot(date,Sub_metering_1,type="l",col="Black",xlab="",ylab=""))
with(EC,lines(date,Sub_metering_2,type="l",col="Blue"))
with(EC,lines(date,Sub_metering_3,type="l",col="Red"))
colors <- c("black", "red", "blue")
labels <- c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3")
title(ylab="Energy sub metering",xlab="")
legend("topright",legend=labels,col=colors,lty="solid")
dev.off()